language: node_js
os:
  - linux
node_js:
  - iojs
  - node
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y p7zip-full
before_script:
  - export TRAVIS=1
  - npm install -g gulp
  - npm install
  - gulp install
script:
  - gulp build
  - gulp build_plugins
